title: Alice Tat
email: tattam192@gmail.com
description: >-
  Hello! I'm currently a Master's student at Deakin University, 
  passionate about software development and continuously enhancing my skills and knowledge in the field.

domain: tut888.github.io
url: https://tut888.github.io
github_username: tut888
linkedin_user: alice-tat
owner_name: Alice

# Build settings
github: [metadata]
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed