title: Alice Tat
email: tattam192@gmail.com
description: >-
  Hello! I am currently pursuing a Master's degree at Deakin University, 
  with a strong passion for software development and a commitment to continually enhancing my skills and knowledge in the field

domain: tut888.github.io
url: https://tut888.github.io
github_username: tut888
linkedin_user: alice-tat
owner_name: Alice

# Build settings
github: [metadata]
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed